name: Docker Build & Push

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build, Tag and Push
        uses: albal/github-actions-docker-publish@0.1.2
        with:
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Contentful/Dockerfile
